_target_: pytorch_lightning.Trainer


# マルチGPU処理にするか
accelerator: "auto"
devices: [0,1]
# devices: "???" # 使用するGPUを実行時に動的に得る場合はこっち

# strategy: "ddp"  #DDP処理したい場合は更に追加
# num_nodes: 1

min_epochs: 1
max_epochs: 200

# PytorchLightningのTrainerにはこんなのがある？要確認
val_check_interval: 100


# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
resume_from_checkpoint: null
