# _target_: src.models.mnist_module.MNISTLitModule
_target_: src.dqn_lightning_module.DQNLitModule

net:
  _target_: src.models.q_net.QNet
  input_size: ${state_size}  #QNetの入力は状態(観測)なので, 状態数を代入
  lin1_size: 128
  lin2_size: 128
  output_size: ${action_size} #QNetの出力は, 入力した状態における各行動のQ関数値なので、行動数を代入

optimizer_namelist: ${optimizer_namelist}

batch_size: ${batch_size}
lr: ${lr}
# weight_decay: ${weight_decay}
env: ${env}
gamma: ${gamma}
sync_rate: ${sync_rate}
replay_size: ${replay_size}
warm_start_size: ${warm_start_size}
eps_last_frame: ${eps_last_frame}
eps_start: ${eps_start}
eps_end: ${eps_end}
episode_length: ${episode_length}
warm_start_steps: ${warm_start_steps}